[package]
name = "iboardbot-web"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
rocket = "0.2.4"
rocket_codegen = "0.2.4"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[dependencies.svg2polylines]
version = "0.1.1"
features = ["use_serde"]

[dependencies.rocket_contrib]
version = "0.2.4"
default-features = false
features = ["json"]
