version: 2
jobs:
  test:
    docker:
      - image: rust:1.31
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ .Branch }}
            - v1-cargo-cache-{{ arch }}
      - run:
          name: Show versions
          command: rustc --version && cargo --version
      - run:
          name: Build
          command: cargo build
      - run:
          name: Run tests
          command: cargo test
      - save_cache:
          key: v1-cargo-cache-{{ arch }}-{{ .Branch }}
          paths:
            - target
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ arch }}
          paths:
            - target
            - /usr/local/cargo
  audit:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-audit-cache
      - run:
          name: Install cargo-audit
          command: cargo install --force cargo-audit
      - run:
          name: Run cargo-audit
          command: cargo audit
      - save_cache:
          key: v1-cargo-audit-cache
          paths:
            - /usr/local/cargo
  build-image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build \
              --no-cache \
              -t dbrgn/iboardbot-web:latest \
              -t dbrgn/iboardbot-web:${CIRCLE_BRANCH} \
              .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && \
            docker push dbrgn/iboardbot-web

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - audit
      - build-image:
          requires:
            - test
          filters:
            branches:
              only:
                - master

  # Build master every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - audit
      - build-image:
          requires:
            - test
