name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-node@v3
      with:
        node-version: current
        cache: npm
    - name: Install Frontend Dependencies
      run: npm ci
    - name: Build Frontend
      run: npm run build
    - name: Update Rust
      run: rustup install stable
    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo test --verbose
